---

name: "Moodle Plugin Changelog Generator"
author: "Aprende DEVOPS <devops@aprende.com>"
description: "Creates a changelog based on the commits using Angular Convention"

inputs:
  path:
    description: "Path where the repository is located"
    default: '.'
  filename:
    description: "Name of the changelog file to write"
    default: 'CHANGELOG.md'

outputs:
  changelog:
    description: "A changelog file"

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'book'
  color: 'blue'
